name: aliorders
description: An app to track the buyer protection period of AliExpress orders

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  sqflite: ^1.3.2
  path_provider: ^1.6.27
  flutter_local_notifications: ^4.0.1+2
  workmanager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter:
  uses-material-design: true
  assets:
    - assets/img/courier.png

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/img/logo.png"
